# server Configuration
server:
  servlet:
    context-path: /lims
  port: 80

# spring Configuration
spring:
  # DB Configuration
  datasource:
    password: 199612034532Wyt
    url: jdbc:mysql://rm-bp12yhr4bu4nn8dslco.mysql.rds.aliyuncs.com:3306/lims

# show sql in console
logging:
  level:
    com.wyt.labinformationmanagementsystem.mapper.*: debug
