# server Configuration
server:
  servlet:
    context-path: /lims
  port: 8888

# spring Configuration
spring:
  # DB Configuration
  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost/lims

# show sql in console
logging:
  level:
    com.wyt.labinformationmanagementsystem.mapper.*: debug
